Run unittest with Python 3.14
$ ./docker/build.sh py314-pytest

======================================================================
FAIL: test_make_source
(tests.TestMakefile.MakefileTestCase.test_make_source)
Test Makefile for source distribution
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/src/tests/TestMakefile.py", line 98, in test_make_source
    self.assertEqual(rc, 0, stderr)
    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
AssertionError: 2 != 0 : make[1]: *** [Makefile:13: require-gettext]
Error 1
make: *** [Makefile:79: install] Error 2

======================================================================
FAIL: test_localization_paths
(tests.TestUnix.UnixTestCase.test_localization_paths)
Unit test for localization_paths()
----------------------------------------------------------------------
Traceback (most recent call last):
File "/tmp/src/tests/TestUnix.py", line 575, in
test_localization_paths
self.assertGreater(counter, 0, 'Zero files deleted by localization
cleaner. ' +
~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
'This may be an error unless you
really deleted all the files.')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError: 0 not greater than 0 : Zero files deleted by
localization cleaner. This may be an error unless you really deleted all
the files.

----------------------------------------------------------------------
Ran 401 tests in 67.358s